name: Type Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "22 4 * * 1"

permissions:
  contents: read

jobs:
  pyrefly:
    name: Pyrefly
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Install uv and set Python version
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        python-version: "3.10"
        activate-environment: true
    - name: Install dependencies
      run: uv sync --locked --group dev --inexact
    - name: Run Pyrefly
      run: uv run pyrefly check --output-format=github
